name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.3"
          bundler: "2.6.9"
          bundler-cache: true

      - name: Scan Rails security vulnerabilities
        run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.3"
          bundler: "2.6.9"
          bundler-cache: true

      - name: Scan JavaScript dependencies
        run: bundle exec importmap audit

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.3"
          bundler: "2.6.9"
          bundler-cache: true

      - name: Lint Ruby code
        run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y \
            google-chrome-stable \
            curl \
            libjemalloc2 \
            libvips \
            sqlite3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.3"
          bundler: "2.6.9"
          bundler-cache: true

      - name: Prepare test database
        env:
          RAILS_ENV: test
        run: bundle exec rails db:test:prepare

      - name: Run unit and integration tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test

      - name: Run system tests
        env:
          RAILS_ENV: test
        run: bundle exec rails test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
